server:
  port: 80
spring:
  application:
    name: goodskill-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: mongotest
        uri: lb://mongo-service-provider
        predicates:
        - Query=red
        filters:
        - JwtAuth

#        - RemoteAddr=172.21.12.1/24
#      routes:
#      - id: es-service
#        uri: lb://es-service-provider
#        predicates:
#        - Path=/yml/**
#        filters:
#        - StripPrefix=1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

