name: Docker publish latest
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ktb_build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: copy fat jar
        run: cp ./target/kafka-topology-builder.jar release/docker
      - name: copy runner file
        run: cp ./src/main/scripts/kafka-topology-builder.sh release/docker
      - name: list files (release dir)
        run: ls -l
        working-directory: release/docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: release/docker
          file: release/docker/Dockerfile
          push: true
          tags: purbon/kafka-topology-builder:latest
